### ISSUE TITLE
Request for data link

### ISSUE THREAD

**Issue by Peregalli** [wonje-Jang/github_SeRMdataset#2]
Dear Wonje Jang,

I hope this message finds you well.

I would like to extend my congratulations on your paper. I found your work very interesting and believe that the data you have compiled could greatly contribute to my ongoing project aimed at conducting a comprehensive survey of the streets in Montevideo, Uruguay.

Despite having previously reached out to the contact email, unfortunately, I did not receive a response. Therefore, I am writing to kindly request your assistance in obtaining access to the relevant data. I would be very grateful if you could provide me with the necessary link or information to access the data repository.

My email address for correspondence is agustina.diaz@fing.edu.uy.

Thank you very much for considering my request. I look forward to your reply.

Regards,

Agustina

**Comment by SeRM-dataset** [comment]
Hello.
This is Wonje Jang.

Sorry for the late reply.

The reply was late because there was a problem with the server.
Thank you for your understanding.

I appreciate you for your interest in our paper and dataset.
Here's the link for downloads:

>> Link
SeRMdataset
<https://drive.google.com/drive/folders/14w4zUYYD1pTwVQbDdDBBct6UKWybnn9s?usp=sharing>

Additionally, RMNet is a network model designed by ourselves.

If there is a problem with the download, please email again.
Also, if you want to see a detailed description of the dataset and an
explanation of validation, please visit our GitHub (
https://github.com/SeRM-dataset/dataset).

Best Regards
Sincerely,
Wonje Jang



*JANG WONJEComputational Intelligence Lab.*School of Electrical &
Electronic Engineering,
Yonsei University, Korea
E-mail : ***@***.***
Cell : +82 10-8630-8683
Office : +82 2-2123-7729


2024년 3월 20일 (수) 오전 5:35, Agustina Diaz ***@***.***>님이 작성:

**Comment by Peregalli** [comment]
Thanks for your reply! I will try to download the data!

**Comment by Peregalli** [comment]
Thanks for your reply! I will try to download the data!
